language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- npm i

jobs:
    include:
      - stage: npm release
        if: tag IS present
        node_js: "10"
        deploy:
          provider: npm
          email: "$NPM_EMAIL"
          api_key: "$NPM_TOKEN"
          skip_cleanup: true
          on:
            tags: true